version: "3.9"
services:
  zeitplanner:
    build: .
    container_name: zeitplanner
    volumes:
      - ./settings.json:/app/settings.json
      - ./plans.json:/app/plans.json
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    networks:
      - default
      - internal_web

networks:
  internal_web:
    external: true