version: "3.9"
services:
  zeitplanner:
    build: .
    container_name: zeitplanner
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - DATA_DIR=/data
    volumes:
      - ./data:/data
    ports:
      - "5492:5000"
    networks:
      - default
      - internal_web

networks:
  internal_web:
    external: true
